### ISSUE TITLE
Lost the ability to release to the GitHub Marketplace

### ISSUE THREAD

**Issue by KevinGDialpad** [talkiq/confluence-wiki-sync#68]
![image](https://github.com/user-attachments/assets/80e18df3-4a67-4a3b-841b-2eecb4f94d42)

We did that when the script was first uploaded, and it was working a year ago when I made the v1.2 release.

**Comment by KevinGDialpad** [comment]
@TheKevJames would you be able to help me here? :)

**Comment by KevinGDialpad** [comment]
You know what, I'm not sure that this is that disruptive. It means that https://github.com/marketplace/actions/confluence-docs-sync is stuck on v1.2 from 2022, but it you do 
```
      - name: Wiki Sync
        uses: talkiq/confluence-wiki-sync@v1
```
like the README says, you target the [v1 branch](https://github.com/talkiq/confluence-wiki-sync/commits/v1/), which follows the latest v1.x tag as explained in MAINTAINING.rst.

**Comment by TheKevJames** [comment]
I believe I've clicked the right set of buttons to resolve this, please retry!

**Comment by KevinGDialpad** [comment]
You did! Thanks a lot @TheKevJames!
